'use server'

// Import all server functions into a single namespace
import * as serverActions from '@headlines/actions'

// Explicitly re-export each function.
// This makes the module compliant with the "use server" directive's rules.
export const {
  loginUser,
  getAdminArticles,
  updateAdminArticle,
  deleteAdminArticle,
  getAdminEvents,
  getAdminEventDetails,
  updateAdminEvent,
  deleteAdminEvent,
  getAdminOpportunities,
  updateAdminOpportunity,
  deleteAdminOpportunity,
  deleteArticle,
  getArticles,
  getTotalArticleCount,
  deleteEvent,
  getEvents,
  getTotalEventCount,
  getOpportunities,
  getTotalOpportunitiesCount,
  deleteOpportunity,
  getOpportunityDetails,
  getUniqueOpportunityCountries,
  sendItemByEmail,
  exportOpportunitiesToCSV,
  exportOpportunitiesToXLSX,
  exportUsersToCSV,
  exportUsersToXLSX,
  exportEventsToCSV,
  exportEventsToXLSX,
  exportArticlesToCSV,
  exportArticlesToXLSX,
  linkOpportunityToEvent,
  unlinkOpportunityFromEvent,
  clearDiscardedItems,
  updateUserProfile,
  updateUserInteraction,
  updateUserFilterPreference,
  getCurrentSubscriber,
  savePushSubscription,
  getAllCountries,
  createCountry,
  updateCountry,
  getGlobalCountries,
  getAllSubscribers,
  createSubscriber,
  updateSubscriber,
  deleteSubscriber,
  updateSubscribersStatus,
  deleteSubscribers,
  getAllSources,
  createSource,
  updateSource,
  deleteSource,
  getDashboardStats,
  getRecentRunVerdicts,
  getRunVerdictById,
  getSuggestions,
  processWatchlistSuggestion,
  processSourceSuggestion,
  updateWatchlistSuggestion,
  getAllWatchlistEntities,
  createWatchlistEntity,
  updateWatchlistEntity,
  deleteWatchlistEntity,
  getSettings,
  updateSettings,
  testSourceConfig,
  updateSourceAnalyticsBatch,
  findSourcesForScraping,
  performHousekeeping,
  bulkWriteEvents,
  bulkWriteArticles,
  findEventsByKeys,
  findArticlesByLinks,
  getActiveWatchlistEntityNames,
  bulkWriteWatchlistSuggestions,
  generateChatTitle,
  suggestSections,
  suggestSelector,
} = serverActions
